name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Swift version
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '6.1.0'
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --no-parallel